In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("work_from_home_burnout_dataset.csv")

In [4]:
df.head()

,user_id,day_type,work_hours,screen_time_hours,meetings_count,breaks_taken,after_hours_work,sleep_hours,task_completion_rate,burnout_score,burnout_risk
0,1,Weekday,9.59,11.86,4,2,0,7.55,91.2,19.17,Low
1,1,Weekend,7.38,10.33,4,1,0,6.69,82.0,29.70,Low
2,1,Weekend,6.31,8.92,1,2,0,8.87,80.6,32.93,Low
3,1,Weekday,8.34,10.70,4,1,1,8.13,70.0,45.47,Low
4,1,Weekend,6.97,9.83,1,2,0,5.85,67.1,51.61,Low

In [5]:
df.shape

(1800, 11)

In [6]:
df.info()
df.describe()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   user_id               1800 non-null   int64
 1   day_type              1800 non-null   object
 2   work_hours            1800 non-null   float64
 3   screen_time_hours     1800 non-null   float64
 4   meetings_count        1800 non-null   int64
 5   breaks_taken          1800 non-null   int64
 6   after_hours_work      1800 non-null   int64
 7   sleep_hours           1800 non-null   float64
 8   task_completion_rate  1800 non-null   float64
 9   burnout_score         1800 non-null   float64
 10  burnout_risk          1800 non-null   object
dtypes: float64(5), int64(4), object(2)
memory usage: 154.8+ KB

,user_id,day_type,work_hours,screen_time_hours,meetings_count,breaks_taken,after_hours_work,sleep_hours,task_completion_rate,burnout_score,burnout_risk
0,1,Weekday,9.59,11.86,4,2,0,7.55,91.2,19.17,Low
1,1,Weekend,7.38,10.33,4,1,0,6.69,82.0,29.70,Low
2,1,Weekend,6.31,8.92,1,2,0,8.87,80.6,32.93,Low
3,1,Weekday,8.34,10.70,4,1,1,8.13,70.0,45.47,Low
4,1,Weekend,6.97,9.83,1,2,0,5.85,67.1,51.61,Low

In [7]:
df.isnull().sum()

user_id                 0
day_type                0
work_hours              0
screen_time_hours       0
meetings_count          0
breaks_taken            0
after_hours_work        0
sleep_hours             0
task_completion_rate    0
burnout_score           0
burnout_risk            0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df = df.drop_duplicates()

In [11]:
df[['work_hours','screen_time_hours','sleep_hours']].describe()

        work_hours  screen_time_hours  sleep_hours
count  1800.000000        1800.000000  1800.000000
mean      6.515117           9.271406     6.996467
std       2.290521           2.409253     1.061740
min       3.000000           4.510000     4.500000
25%       4.430000           7.240000     6.280000
50%       6.445000           9.210000     6.990000
75%       8.510000          11.310000     7.750000
max      12.170000          15.700000    10.800000

In [12]:
df['burnout_risk'] = df['burnout_risk'].str.strip().str.title()

In [13]:
df['productivity_index'] = df['task_completion_rate'] / df['work_hours']

In [14]:
df['work_intensity'] = df['screen_time_hours'] + df['meetings_count']

In [15]:
df['after_hours_work'] = df['after_hours_work'].map({0: 'No', 1: 'Yes'})

In [16]:
df.info()
df.isnull().sum()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   user_id               1800 non-null   int64
 1   day_type              1800 non-null   object
 2   work_hours            1800 non-null   float64
 3   screen_time_hours     1800 non-null   float64
 4   meetings_count        1800 non-null   int64
 5   breaks_taken          1800 non-null   int64
 6   after_hours_work      1800 non-null   object
 7   sleep_hours           1800 non-null   float64
 8   task_completion_rate  1800 non-null   float64
 9   burnout_score         1800 non-null   float64
 10  burnout_risk          1800 non-null   object
 11  productivity_index    1800 non-null   float64
 12  work_intensity        1800 non-null   float64
dtypes: float64(7), int64(3), object(3)
memory usage: 182.9+ KB

(1800, 13)

In [17]:
df.to_csv("cleaned_burnout_dataset.csv", index=False)

In [18]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [19]:
df

      user_id day_type  work_hours  screen_time_hours  meetings_count  \
0           1  Weekday        9.59              11.86               4
1           1  Weekend        7.38              10.33               4
2           1  Weekend        6.31               8.92               1
3           1  Weekday        8.34              10.70               4
4           1  Weekend        6.97               9.83               1
5           1  Weekday        7.24               9.09               1
6           1  Weekday        8.09              11.64               6
7           1  Weekday        7.15               9.98               3
8           1  Weekday        8.72              11.80               1
9           1  Weekend        5.93               9.17               0
10          2  Weekend        3.00               6.81               3
11          2  Weekday        7.96              11.25               3
12          2  Weekend        5.05               7.38               0
13          2  Weekend        3.79               6.12               3
14          2  Weekend        4.69               7.09               1
15          2  Weekend        3.00               5.05               0
16          2  Weekday        6.49               9.60               3
17          2  Weekday       10.04              11.83               3
18          2  Weekend        3.12               5.08               0
19          2  Weekday        6.83               8.81               7
20          3  Weekend        4.49               6.53               2
21          3  Weekend        5.47               8.10               2
22          3  Weekday        7.71              11.12               1
23          3  Weekday        8.94              12.85               4
24          3  Weekday        6.99               8.58               1
25          3  Weekday        7.69               9.70               6
26          3  Weekday       10.01              13.75               3
27          3  Weekend        3.85               7.57               1
28          3  Weekend        4.31               7.55               3
29          3  Weekend        5.54               8.48               2
30          4  Weekday        9.43              12.64               3
31          4  Weekend        3.81               7.40               2
32          4  Weekend        4.60               6.58               0
33          4  Weekend        5.42               7.17               1
34          4  Weekend        5.50               9.35               2
35          4  Weekend        3.28               5.87               1
36          4  Weekend        4.91               8.74               0
37          4  Weekday        9.24              11.96               2
38          4  Weekend        6.05               7.89               1
39          4  Weekday        9.01              12.18               4
40          5  Weekday       10.73              12.33               3
41          5  Weekend        5.59               7.20               0
42          5  Weekend        3.78               6.39               1
43          5  Weekend        6.54               9.05               1
44          5  Weekday       10.00              13.71               1
45          5  Weekend        4.09               5.96               0
46          5  Weekend        3.36               5.03               2
47          5  Weekday        6.92               9.62               1
48          5  Weekday        8.91              12.54               5
49          5  Weekend        4.74               8.49               0
50          6  Weekend        4.78               6.56               2
51          6  Weekday        6.12               9.64               2
52          6  Weekday        8.82              11.33               4
53          6  Weekend        4.22               7.35               2
54          6  Weekend        5.65               7.69               2
55          6  Weekend        3.34               5.52               0
56          6  Weekend        4.03               6.54               0
57          6  Weekday        9.56              11.94               3
58          6  Weekday        8.01              10.18               6
59          6  Weekend        3.49               5.13               1
60          7  Weekend        3.74               6.03               0
61          7  Weekend        5.89               9.56               2
62          7  Weekday        7.24               9.94               3
63          7  Weekday        9.34              13.04               4
64          7  Weekend        4.63               6.32               2
65          7  Weekend        3.94               7.56               1
66          7  Weekday        8.74              10.26               2
67          7  Weekday        7.20               9.54               0
68          7  Weekday        8.49              11.63               2
69          7  Weekend        3.71               7.38               1
70          8  Weekend        4.14               7.09               1
71          8  Weekend        6.84               8.77               1
72          8  Weekday        7.88               9.67               2
73          8  Weekday        7.13              10.22               6
74          8  Weekend        6.62               8.82               0
75          8  Weekend        3.00               5.54               1
76          8  Weekend        6.34               9.65               0
77          8  Weekday        9.00              11.49               5
78          8  Weekday        7.69              10.24               4
79          8  Weekend        3.91               7.38               0
80          9  Weekend        6.89               9.89               1
81          9  Weekend        4.01               6.06               2
82          9  Weekday        9.24              12.51               0
83          9  Weekend        3.49               5.18               1
84          9  Weekend        3.94               6.10               0
85          9  Weekend        3.00               6.45               2
86          9  Weekend        3.88               7.04               0
87          9  Weekend        5.19               8.24               0
88          9  Weekend        5.03               9.03               0
89          9  Weekday        5.98               8.84               2
90         10  Weekend        4.33               7.87               0
91         10  Weekday        8.29              10.67               2
92         10  Weekend        4.60               6.84               2
93         10  Weekday        8.07               9.92               6
94         10  Weekday        6.18               8.02               4
95         10  Weekend        4.75               7.27               0
96         10  Weekend        3.00               4.52               0
97         10  Weekday        8.29              10.24               2
98         10  Weekday        7.78              10.90               4
99         10  Weekend        5.34               8.84               1
100        11  Weekday        6.85               9.33               0
101        11  Weekday        7.70              10.39               3
102        11  Weekday        6.58              10.54               0
103        11  Weekend        5.77               9.67               1
104        11  Weekend        3.98               7.67               0
105        11  Weekend        4.81               8.61               1
106        11  Weekend        5.32               8.85               1
107        11  Weekend        5.13               7.50               1
108        11  Weekday        8.78              10.64               0
109        11  Weekday        9.19              12.68               1
110        12  Weekday        8.16              11.70               4
111        12  Weekend        5.08               8.75               1
112        12  Weekday        7.97              11.00               5
113        12  Weekend        5.59               8.54               2
114        12  Weekday        8.62              12.18               3
115        12  Weekend        3.00               5.23               2
116        12  Weekend        3.00               5.22               0
117        12  Weekend        5.29               8.80               1
118        12  Weekend        3.73               5.91               1
119        12  Weekend        3.00               4.76               0
120        13  Weekday        8.88              12.02               5
121        13  Weekday        9.22              12.23               1
122        13  Weekday        8.74              10.66               5
123        13  Weekend        5.06               7.74               2
124        13  Weekend        5.65               8.62               2
125        13  Weekend        3.86               7.76               1
126        13  Weekday        7.14              10.72               2
127        13  Weekday       10.04              13.72               1
128        13  Weekend        4.74               6.71               2
129        13  Weekend        3.00               5.08               2
130        14  Weekend        3.00               5.17               1
131        14  Weekend        4.24               8.15               2
132        14  Weekend        5.05               8.50               1
133        14  Weekday        9.76              13.69               2
134        14  Weekday        7.53              10.90               1
135        14  Weekday        8.03              11.08               2
136        14  Weekday        7.88              10.44               3
137        14  Weekend        5.13               8.16               2
138        14  Weekend        4.08               7.27               1
139        14  Weekend        4.40               8.24               2
140        15  Weekday        8.02              11.61               4
141        15  Weekend        4.71               7.84               2
142        15  Weekday        7.56               9.28               2
143        15  Weekday        8.89              11.58               7
144        15  Weekday        8.83              12.06               2
145        15  Weekday        9.96              13.02               3
146        15  Weekend        5.20               8.68               2
147        15  Weekday        7.87              10.43               4
148        15  Weekday        9.05              11.45               2
149        15  Weekday        5.69               9.32               0
150        16  Weekday       10.13              13.13               2
151        16  Weekend        4.93               8.07               0
152        16  Weekend        3.00               6.33               1
153        16  Weekend        3.37               7.25               2
154        16  Weekday        8.48              11.67               3
155        16  Weekday        6.97               9.21               2
156        16  Weekday        7.93              10.56               2
157        16  Weekday       10.09              11.81               1
158        16  Weekend        4.74               8.71               1
159        16  Weekday        7.87              10.80               2
160        17  Weekend        5.41               8.00               1
161        17  Weekday        8.18              11.19               3
162        17  Weekday        8.83              12.00               2
163        17  Weekend        3.70               6.45               1
164        17  Weekday        7.14              10.24               1
165        17  Weekday        8.18              10.71               8
166        17  Weekend        6.35               7.94               1
167        17  Weekday        8.93              10.99               2
168        17  Weekend        4.64               6.18               1
169        17  Weekend        5.82               7.88               0
170        18  Weekday        9.89              12.69               1
171        18  Weekday        6.76              10.07               3
172        18  Weekday        7.71              10.43               4
173        18  Weekend        3.95               7.19               1
174        18  Weekday        6.44              10.38               2
175        18  Weekday        9.36              11.61               4
176        18  Weekend        3.08               5.72               0
177        18  Weekend        3.32               6.19               0
178        18  Weekday        8.69              11.15               2
179        18  Weekend        3.35               5.57               3
180        19  Weekday        7.88              11.39               4
181        19  Weekday        8.65              10.52               5
182        19  Weekend        4.05               6.41               1
183        19  Weekday       10.07              11.93               1
184        19  Weekday        9.07              12.06               3
185        19  Weekday        8.74              12.36               0
186        19  Weekend        4.87               6.47               1
187        19  Weekday        8.51              10.34               3
188        19  Weekend        4.19               5.88               0
189        19  Weekend        3.00               6.27               1
190        20  Weekend        4.02               6.25               1
191        20  Weekend        3.00               6.94               1
192        20  Weekend        4.89               7.58               3
193        20  Weekday        7.92              11.19               2
194        20  Weekend        4.80               7.90               2
195        20  Weekend        4.40               7.86               0
196        20  Weekend        5.10               7.15               2
197        20  Weekend        4.32               5.88               1
198        20  Weekday        6.87               9.97               1
199        20  Weekday        9.33              12.35               4
200        21  Weekend        5.97               8.73               0
201        21  Weekend        4.63               6.80               0
202        21  Weekend        6.83               8.38               1
203        21  Weekend        6.85               8.53               2
204        21  Weekend        5.35               7.41               0
205        21  Weekend        4.51               7.58               2
206        21  Weekend        4.56               7.30               1
207        21  Weekend        3.83               7.12               1
208        21  Weekday        9.91              13.76               3
209        21  Weekend        6.58              10.51               2
210        22  Weekday        9.82              12.08               1
211        22  Weekday        9.68              13.48               5
212        22  Weekend        5.81               7.99               2
213        22  Weekday        7.91              11.02               4
214        22  Weekend        4.90               8.73               0
215        22  Weekend        6.91              10.31               1
216        22  Weekday        8.22               9.97               6
217        22  Weekday        5.37               8.70               2
218        22  Weekend        4.71               7.96               1
219        22  Weekday        6.99               9.09               2
220        23  Weekday       11.64              15.41               2
221        23  Weekend        3.27               5.89               0
222        23  Weekend        4.32               6.48               0
223        23  Weekday        7.65               9.45               1
224        23  Weekend        5.81               7.87               3
225        23  Weekday        9.43              13.38               4
226        23  Weekday        7.85               9.78               2
227        23  Weekday        7.84              11.22               1
228        23  Weekday        7.57               9.55               6
229        23  Weekend        3.75               6.23               1
230        24  Weekday        7.37              10.76               5
231        24  Weekend        3.07               6.94               0
232        24  Weekday        8.26              11.99               3
233        24  Weekday        6.54               9.15               1
234        24  Weekend        3.66               7.03               1
235        24  Weekday        9.72              12.32               2
236        24  Weekend        5.51               7.23               3
237        24  Weekday        9.06              11.33               2
238        24  Weekend        3.40               6.44               2
239        24  Weekday        9.53              11.62               3
240        25  Weekday        9.02              11.16               5
241        25  Weekday        7.46               9.58               2
242        25  Weekend        3.18               6.96               3
243        25  Weekday        8.38              11.19               3
244        25  Weekday        9.51              12.64               5
245        25  Weekday        8.24              11.08               2
246        25  Weekend        4.44               7.80               0
247        25  Weekday        8.65              11.20               3
248        25  Weekend        4.92               8.39               1
249        25  Weekday        8.63              12.01               2
250        26  Weekend        5.83               8.20               1
251        26  Weekend        5.13               8.29               1
252        26  Weekday        7.69              11.26               2
253        26  Weekend        5.07               6.79               2
254        26  Weekend        6.49              10.12               1
255        26  Weekend        6.55               8.34               1
256        26  Weekend        4.33               5.87               1
257        26  Weekend        4.16               7.26               0
258        26  Weekend        3.00               5.75               1
259        26  Weekday        8.12              12.11               4
260        27  Weekend        3.87               7.47               0
261        27  Weekday        9.38              12.82               3
262        27  Weekend        3.00               6.94               0
263        27  Weekday        8.17               9.72               4
264        27  Weekday        8.49              11.91               5
265        27  Weekend        3.00               5.40               2
266        27  Weekend        4.54               8.37               0
267        27  Weekday        8.86              10.65               2
268        27  Weekday        7.74              10.91               3
269        27  Weekend        3.18               4.76               1
270        28  Weekday        7.26               9.03               2
271        28  Weekend        4.52               7.89               0
272        28  Weekday        8.60              12.60               2
273        28  Weekday        8.16              11.09               2
274        28  Weekend        3.35               5.67               0
275        28  Weekday        8.48              11.80               3
276        28  Weekday        9.07              10.84               3
277        28  Weekday        7.76              11.02               3
278        28  Weekend        4.16               6.93               1
279        28  Weekend        3.45               5.01               0
280        29  Weekday        9.65              11.49               1
281        29  Weekday        8.99              10.66               4
282        29  Weekend        5.06               6.93               1
283        29  Weekday        8.66              10.58               1

## 📘 Data Dictionary

| Column Name | Description | Data Type |
|-------------|------------|----------|
| user_id | Unique identifier for each employee | Integer |
| day_type | Indicates whether the day is a weekday or weekend | Categorical |
| work_hours | Number of hours worked in a day | Float |
| screen_time_hours | Total hours spent in front of screen | Float |
| meetings_count | Number of meetings attended in a day | Integer |
| breaks_taken | Number of breaks taken during work hours | Integer |
| after_hours_work | Indicates if employee worked after office hours (Yes/No) | Categorical |
| sleep_hours | Number of hours slept per day | Float |
| task_completion_rate | Percentage of tasks completed | Float |
| burnout_score | Calculated burnout intensity score | Float |
| burnout_risk | Category of burnout risk (Low/Medium/High) | Categorical |
| productivity_index | Derived feature: task completion rate per work hour | Float |
| work_intensity | Derived feature: screen time hours + meetings count | Float |